config/routes.rb
Rails.application.routes.draw do
  resources :comments, except: [:edit]
  resources :posts, except: [:edit, :update]
  root 'posts#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :body, :name, presence: true
end

app/models/post.rb
class Post < ApplicationRecord
end
  

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment, notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end
  

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def comment_params
      params.require(:comment).permit(:email, :body, :url, :name)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :destroy]
  
  def index
    @posts = Post.all
  end

  def show
  end

  def new
    @post = Post.new 
  end

  def edit
  end
    
  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to @post, notice: 'Post was successfully created.'
    else
      render :new
    end
  end

  def update
    if @post.update(post_params)
      redirect_to @post, notice: 'Post was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @post.destroy
    redirect_to posts_url, notice: 'Post was successfully destroyed.'
  end

  private 
    def set_post
      @post = Post.find(params[:id])
    end

    def post_params
      params.require(:post).permit(:name, :email, :url, :body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_form.html.erb
<%= form_with(model: comment, local: true) do |form| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
        <% comment.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="field">
    <%= form.label :url %>
    <%= form.text_field :url %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Comments</h1>

<table>
  <thead>
    <tr>
      <th>ID</th>
      <th>Email</th>
      <th>Body</th>
      <th>Url</th>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.id %></td>
        <td><%= comment.email %></td>
        <td><%= comment.body %></td>
        <td><%= comment.url %></td>
        <td><%= comment.name %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @comment.email %>
</p>

<p>
  <strong>Body:</strong>
  <%= @comment.body %>
</p>

<p>
  <strong>Url:</strong>
  <%= @comment.url %>
</p>

<p>
  <strong>Name:</strong>
  <%= @comment.name %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
 <head>
    <title>Guestbook</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, height=device-height, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Lato" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css">
    <link type="text/css" rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/froala-design-blocks/2.0.0/css/froala_blocks.min.css">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Hello World</h1>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
<section class="fdb-block-form">
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-12 col-md-8 col-lg-7 col-md-5 text-center">
        <div class="fdb-box fdb-touch">
          <div class="row mt-4 field">
            <div class= "col">
              <%= form.text_field :name, :class => 'form-control', :type => 'text', :placeholder => 'Name' %>
            </div>
          </div>
          <div class="row mt-4 field">
            <div class= "col">
              <%= form.text_field :email, :class => 'form-control', :type => 'text', :placeholder => 'Email' %>
            </div>
          </div>
          <div class="row mt-4 field">
            <div class= "col">
              <%= form.text_field :url, :class => 'form-control', :type => 'text', :placeholder => 'URL' %>
            </div>
          </div>
          <div class="row mt-4 field">
            <div class= "col">
              <%= form.text_field :body, :class => 'form-control', :type => 'text', :placeholder => 'Your Message' %>
            </div>
          </div>
          <div class="row mt-4 actions">
            <div class= "col">
              <%= form.submit :class => 'btn btn-outline-primary-create-new-post' %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
<% end %>

app/views/posts/edit.html.erb
<section class="fdb-block">
  <div class="container">
    <div class="row justify-content-center">
      <div class="col col-md-12">
        <h1 class="edit-your-post">Edit your post</h1>
      </div>
    </div>
  </div>
</section>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %>
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<section class="fdb-block">
  <div class="container">
    <div class="row justify-content-center">
      <div class="col col-md-12">
        <h1>Posts</h1>
        <br>
        <h3 class="lead">A simple guestbook website!</h3>
        <br>
        <h4>Feel free to add your post here.</h4>
      </div>
      <div class="col col-md-12">
        <%= link_to 'New post', new_post_path, :class => 'btn btn-outline-primary-new-post', :type => 'button' %>
      </div>
    </div>
  </div>
</section>


<section class="fdb-block-posts">
  <div class="container pt-sm">
    <table class="table">
      <thead class="thead-dark">
        <tr>
          <th scope="col">Name</th>
          <th scope="col">Email</th>
          <th scope="col">Url</th>
          <th scope="col">Body</th>
          <th colspan="3"></th>
        </tr>
      </thead>
      <tbody>
        <% @posts.each do |post| %>
          <tr>
            <td><%= post.name %></td>
            <td><%= post.email %></td>
            <td><%= post.url %></td>
            <td><%= post.body %></td>
            <td><%= link_to 'Destroy', post, :class => 'btn btn-outline-danger', :type => 'button', method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</section>

<section class="fdb-block-footer">
  <div class="container">
    <div class="row text-center">
      <div class="col-12">
        <h3>Made with <i class="fas fa-heart text-danger"></i> by <a class="alex-rusu" href="https://alex.dutylabs.ro"> Alex Rusu</a></h1>
      </div>
    </div>
  </div>
</section>

app/views/posts/new.html.erb
<section class="fdb-block">
  <div class="container">
    <div class="row justify-content-center">
      <div class="col col-md-8 text-center">
        <h2>New Post</h1>
      </div>
    </div>
  </div>
</section>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"> <%= notice %></p>

<section class="fdb-block py-0">
  <div class="container py-5 my-5">
    <div class="row">
      <div class="col-12 col-md-8 col-lg-7 col-xl-5 text-left">
        <div class="row">
          <div class="col">
            <h1>Your post is live! </h1>
            <h4 class="lead">Thank you for your post!</h4>
            <br>
            <h4 class="lead">Feel free to change something if you change your mind or you can go to Homepage and see your post there. </h4>
          </div>
        </div>
        <div class="fdb-touch-show">  
          <div class="row">
            <div class="col mt-4">
              <strong>Name: </strong>
              <%= @post.name %>
            </div>
          </div>
          <div class="row mt-4">
            <div class="col">
              <strong>Email: </strong>
              <%= @post.email %>
            </div>
          </div>
          <div class="row mt-4">
            <div class="col">
              <strong>Url: </strong>
              <%= @post.url %>
            </div>
          </div>
          <div class="row mt-4">
            <div class="col">
              <strong>Body: </strong>
              <%= @post.body %>
            </div>
          </div>
        </div>
        <div class="row mt-4">
          <%= link_to 'Back', posts_path, :class => 'btn btn-outline-dark-back' %>
        </div>
      </div>
    </div>
  </div>
</section>